package com.xiyu.flash.games.pvz.resources;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
//import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Paint.Align;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.Display;
import android.view.Menu;
import android.view.MenuItem;
import android.view.MotionEvent;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.Window;
import android.view.WindowManager;
import android.graphics.*;

import com.xiyu.util.Array;
import com.xiyu.util.*;

    public class PVZSounds {
        public static  String SOUND_SQUASH_HMM2 ="SOUND_SQUASH_HMM2";
        public static  String SOUND_SHOVEL ="SOUND_SHOVEL";
        public static  String SOUND_GARGANTUAR_THUMP ="SOUND_GARGANTUAR_THUMP";
        public static  String SOUND_CRAZYDAVECRAZY ="SOUND_CRAZYDAVECRAZY";
        public static  String SOUND_CHOMPSOFT ="SOUND_CHOMPSOFT";
        public static  String SOUND_POLEVAULT ="SOUND_POLEVAULT";
        public static  String SOUND_CHERRYBOMB ="SOUND_CHERRYBOMB";
        public static  String SOUND_VASE_BREAKING ="SOUND_VASE_BREAKING";
        public static  String SOUND_BUZZER ="SOUND_BUZZER";
        public static  String SOUND_GRASSSTEP ="SOUND_GRASSSTEP";
        public static  String SOUND_JUICY ="SOUND_JUICY";
        public static  String SOUND_BONK ="SOUND_BONK";
        public static  String SOUND_BIGCHOMP ="SOUND_BIGCHOMP";
        public static  String SOUND_GRAVEBUTTON ="SOUND_GRAVEBUTTON";
        public static  String SOUND_SHIELDHIT ="SOUND_SHIELDHIT";
        public static  String SOUND_CRAZYDAVESHORT2 ="SOUND_CRAZYDAVESHORT2";
        public static  String SOUND_CRAZYDAVESHORT3 ="SOUND_CRAZYDAVESHORT3";
        public static  String SOUND_BUTTONCLICK ="SOUND_BUTTONCLICK";
        public static  String SOUND_CRAZYDAVESHORT1 ="SOUND_CRAZYDAVESHORT1";
        public static  String SOUND_DIGGER_ZOMBIE ="SOUND_DIGGER_ZOMBIE";
        public static  String SOUND_LIMBS_POP1 ="SOUND_LIMBS_POP1";
        public static  String SOUND_LIMBS_POP2 ="SOUND_LIMBS_POP2";
        public static  String SOUND_LIMBS_POP3 ="SOUND_LIMBS_POP3";
        public static  String SOUND_LIMBS_POP4 ="SOUND_LIMBS_POP4";
        public static  String SOUND_LIMBS_POP5 ="SOUND_LIMBS_POP5";
        public static  String SOUND_SIREN ="SOUND_SIREN";
        public static  String SOUND_DIRT_RISE ="SOUND_DIRT_RISE";
        public static  String SOUND_SCREAM ="SOUND_SCREAM";
        public static  String SOUND_AWOOGA ="SOUND_AWOOGA";
        public static  String SOUND_PLASTICHIT ="SOUND_PLASTICHIT";
        public static  String SOUND_SQUASH_HMM ="SOUND_SQUASH_HMM";
        public static  String SOUND_GULP ="SOUND_GULP";
        public static  String SOUND_PLASTICHIT2 ="SOUND_PLASTICHIT2";
        public static  String SOUND_BOWLING ="SOUND_BOWLING";
        public static  String SOUND_TAP ="SOUND_TAP";
        public static  String SOUND_SHIELDHIT2 ="SOUND_SHIELDHIT2";
        public static  String SOUND_NEWSPAPER_RARRGH2 ="SOUND_NEWSPAPER_RARRGH2";
        public static  String SOUND_BOWLINGIMPACT2 ="SOUND_BOWLINGIMPACT2";
        public static  String SOUND_CHOMP ="SOUND_CHOMP";
        public static  String SOUND_POINTS2 ="SOUND_POINTS2";
        public static  String SOUND_POINTS4 ="SOUND_POINTS4";
        public static  String SOUND_POINTS1 ="SOUND_POINTS1";
        public static  String SOUND_POINTS3 ="SOUND_POINTS3";
        public static  String SOUND_SEEDLIFT ="SOUND_SEEDLIFT";
        public static  String SOUND_REVERSE_EXPLOSION ="SOUND_REVERSE_EXPLOSION";
        public static  String SOUND_HUGEWAVE ="SOUND_HUGEWAVE";
        public static  String SOUND_CHOMP2 ="SOUND_CHOMP2";
        public static  String SOUND_TAP2 ="SOUND_TAP2";
        public static  String SOUND_POINTS5 ="SOUND_POINTS5";
        public static  String SOUND_THROW1 ="SOUND_THROW1";
        public static  String SOUND_THROW3 ="SOUND_THROW3";
        public static  String SOUND_READYSETPLANT ="SOUND_READYSETPLANT";
        public static  String SOUND_THROW4 ="SOUND_THROW4";
        public static  String SOUND_LAWNMOWER ="SOUND_LAWNMOWER";
        public static  String SOUND_THROW2 ="SOUND_THROW2";
        public static  String SOUND_PAUSE ="SOUND_PAUSE";
        public static  String SOUND_PLANTGROW ="SOUND_PLANTGROW";
        public static  String SOUND_CRAZYDAVEEXTRALONG1 ="SOUND_CRAZYDAVEEXTRALONG1";
        public static  String SOUND_CRAZYDAVEEXTRALONG2 ="SOUND_CRAZYDAVEEXTRALONG2";
        public static  String SOUND_CRAZYDAVEEXTRALONG3 ="SOUND_CRAZYDAVEEXTRALONG3";
        public static  String SOUND_BOWLINGIMPACT ="SOUND_BOWLINGIMPACT";
        public static  String SOUND_PLANT2 ="SOUND_PLANT2";
        public static  String SOUND_SWING ="SOUND_SWING";
        public static  String SOUND_GROAN ="SOUND_GROAN";
        public static  String SOUND_PRIZE ="SOUND_PRIZE";
        public static  String SOUND_EXPLOSION ="SOUND_EXPLOSION";
        public static  String SOUND_NEWSPAPER_RARRGH ="SOUND_NEWSPAPER_RARRGH";
        public static  String SOUND_GROAN2 ="SOUND_GROAN2";
        public static  String SOUND_GROAN3 ="SOUND_GROAN3";
        public static  String SOUND_GROAN4 ="SOUND_GROAN4";
        public static  String SOUND_GROAN5 ="SOUND_GROAN5";
        public static  String SOUND_GROAN6 ="SOUND_GROAN6";
        public static  String SOUND_SPLAT ="SOUND_SPLAT";
        public static  String SOUND_CRAZYDAVESCREAM ="SOUND_CRAZYDAVESCREAM";
        public static  String SOUND_LOADINGBAR_ZOMBIE ="SOUND_LOADINGBAR_ZOMBIE";
        public static  String SOUND_SPLAT3 ="SOUND_SPLAT3";
        public static  String SOUND_CRAZYDAVELONG1 ="SOUND_CRAZYDAVELONG1";
        public static  String SOUND_CRAZYDAVELONG2 ="SOUND_CRAZYDAVELONG2";
        public static  String SOUND_CRAZYDAVELONG3 ="SOUND_CRAZYDAVELONG3";
        public static  String SOUND_SPLAT2 ="SOUND_SPLAT2";
        public static  String SOUND_ZOMBIE_FALLING_2 ="SOUND_ZOMBIE_FALLING_2";
        public static  String SOUND_PUFF ="SOUND_PUFF";
        public static  String SOUND_BLEEP ="SOUND_BLEEP";
        public static  String SOUND_ROLL_IN ="SOUND_ROLL_IN";
        public static  String SOUND_ZOMBIE_FALLING_1 ="SOUND_ZOMBIE_FALLING_1";
        public static  String SOUND_NEWSPAPER_RIP ="SOUND_NEWSPAPER_RIP";
        public static  String SOUND_GRAVESTONE_RUMBLE ="SOUND_GRAVESTONE_RUMBLE";
        public static  String SOUND_FROZEN ="SOUND_FROZEN";
        public static  String SOUND_LOADINGBAR_FLOWER ="SOUND_LOADINGBAR_FLOWER";
        public static  String SOUND_CRAZYDAVESCREAM2 ="SOUND_CRAZYDAVESCREAM2";
        public static  String SOUND_GRAVEBUSTERCHOMP ="SOUND_GRAVEBUSTERCHOMP";
        public static  String SOUND_PLANT ="SOUND_PLANT";
        public static  String SOUND_SNOW_PEA_SPARKLES ="SOUND_SNOW_PEA_SPARKLES";
        public static  String SOUND_EVILLAUGH ="SOUND_EVILLAUGH";
        public static  String SOUND_FUME ="SOUND_FUME";
        public static  String SOUND_FINALWAVE ="SOUND_FINALWAVE";

    }


