package com.xiyu.flash.games.pvz;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
//import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Paint.Align;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.Display;
import android.view.Menu;
import android.view.MenuItem;
import android.view.MotionEvent;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.Window;
import android.view.WindowManager;
import android.graphics.*;

import com.xiyu.util.Array;
import com.xiyu.util.*;

import com.xiyu.flash.framework.resources.foley.FoleyType;
import com.xiyu.flash.games.pvz.resources.PVZSounds;
import com.xiyu.flash.framework.resources.foley.FoleyFlags;

    public class PVZFoleyType {
    	public static Object[] objs0 ={PVZSounds.SOUND_SPLAT, PVZSounds.SOUND_SPLAT2, PVZSounds.SOUND_SPLAT3};
        public static FoleyType SPLAT = new FoleyType(10, objs0, FoleyFlags.NONE);
    	public static Object[] objs1 ={PVZSounds.SOUND_CRAZYDAVESCREAM};
        public static FoleyType CRAZYDAVESCREAM = new FoleyType(0, objs1, FoleyFlags.NONE);
    	public static Object[] objs2 ={PVZSounds.SOUND_BOWLINGIMPACT2};
        public static FoleyType BOWLINGIMPACT2 = new FoleyType(0, objs2, FoleyFlags.NONE);
    	public static Object[] objs3 ={PVZSounds.SOUND_BLEEP};
        public static FoleyType BLEEP = new FoleyType(0, objs3, FoleyFlags.NONE);
    	public static Object[] objs4 ={PVZSounds.SOUND_ROLL_IN};
        public static FoleyType ROLL_IN = new FoleyType(0, objs4, FoleyFlags.NONE);
    	public static Object[] objs5 ={PVZSounds.SOUND_HUGEWAVE};
        public static FoleyType HUGEWAVE = new FoleyType(0, objs5, FoleyFlags.NONE);
    	public static Object[] objs6 ={PVZSounds.SOUND_POINTS1, PVZSounds.SOUND_POINTS2, PVZSounds.SOUND_POINTS3, PVZSounds.SOUND_POINTS4, PVZSounds.SOUND_POINTS5};
        public static FoleyType SUN = new FoleyType(10, objs6, FoleyFlags.NONE);
    	public static Object[] objs7 ={PVZSounds.SOUND_CRAZYDAVEEXTRALONG1, PVZSounds.SOUND_CRAZYDAVEEXTRALONG2, PVZSounds.SOUND_CRAZYDAVEEXTRALONG3};
        public static FoleyType CRAZYDAVEEXTRALONG = new FoleyType(0, objs7, new FoleyFlags(FoleyFlags.DONT_REPEAT));
    	public static Object[] objs8 ={PVZSounds.SOUND_GRAVESTONE_RUMBLE};
        public static FoleyType GRAVESTONE_RUMBLE = new FoleyType(10, objs8, FoleyFlags.NONE);
    	public static Object[] objs9 ={PVZSounds.SOUND_NEWSPAPER_RIP};
        public static FoleyType NEWSPAPER_RIP = new FoleyType(-2, objs9, FoleyFlags.NONE);
    	public static Object[] objs10 ={PVZSounds.SOUND_PLASTICHIT, PVZSounds.SOUND_PLASTICHIT2};
        public static FoleyType PLASTIC_HIT = new FoleyType(5, objs10, FoleyFlags.NONE);
    	public static Object[] objs11 ={PVZSounds.SOUND_GROAN, PVZSounds.SOUND_GROAN2, PVZSounds.SOUND_GROAN3, PVZSounds.SOUND_GROAN4, PVZSounds.SOUND_GROAN5, PVZSounds.SOUND_GROAN6};
        public static FoleyType BRAINS = new FoleyType(0, objs11, FoleyFlags.NONE);
    	public static Object[] objs12 ={PVZSounds.SOUND_VASE_BREAKING};
        public static FoleyType VASE_BREAKING = new FoleyType(-5, objs12, FoleyFlags.NONE);
    	public static Object[] objs13 ={PVZSounds.SOUND_THROW1};
        public static FoleyType SPAWN_SUN = new FoleyType(10, objs13, FoleyFlags.NONE);
    	public static Object[] objs14 ={PVZSounds.SOUND_PLANT, PVZSounds.SOUND_PLANT2};
        public static FoleyType PLANT = new FoleyType(0, objs14, FoleyFlags.NONE);
    	public static Object[] objs15 ={PVZSounds.SOUND_SNOW_PEA_SPARKLES};
        public static FoleyType SNOW_PEA_SPARKLES = new FoleyType(10, objs15, FoleyFlags.NONE);
    	public static Object[] objs16 ={PVZSounds.SOUND_EVILLAUGH};
        public static FoleyType EVILLAUGH = new FoleyType(5, objs16, FoleyFlags.NONE);
    	public static Object[] objs17 ={PVZSounds.SOUND_JUICY};
        public static FoleyType JUICY = new FoleyType(2, objs17, FoleyFlags.NONE);
    	public static Object[] objs18 ={PVZSounds.SOUND_NEWSPAPER_RARRGH, PVZSounds.SOUND_NEWSPAPER_RARRGH2, PVZSounds.SOUND_NEWSPAPER_RARRGH2};
        public static FoleyType NEWSPAPER_RARRGH = new FoleyType(-2, objs18, FoleyFlags.NONE);
    	public static Object[] objs19 ={PVZSounds.SOUND_GRAVEBUTTON};
        public static FoleyType GRAVEBUTTON = new FoleyType(0, objs19, FoleyFlags.NONE);
    	public static Object[] objs20 ={PVZSounds.SOUND_POLEVAULT};
        public static FoleyType POLEVAULT = new FoleyType(0, objs20, FoleyFlags.NONE);
    	public static Object[] objs21 ={PVZSounds.SOUND_SIREN};
        public static FoleyType SIREN = new FoleyType(0, objs21, FoleyFlags.NONE);
    	public static Object[] objs22 ={PVZSounds.SOUND_FINALWAVE};
        public static FoleyType FINALWAVE = new FoleyType(0, objs22, FoleyFlags.NONE);
    	public static Object[] objs23 ={PVZSounds.SOUND_ZOMBIE_FALLING_1, PVZSounds.SOUND_ZOMBIE_FALLING_2};
        public static FoleyType ZOMBIE_FALLING = new FoleyType(10, objs23, FoleyFlags.NONE);
    	public static Object[] objs24 ={PVZSounds.SOUND_PLANT2};
        public static FoleyType USE_SHOVEL = new FoleyType(0, objs24, FoleyFlags.NONE);
    	public static Object[] objs25 ={PVZSounds.SOUND_CHOMPSOFT};
        public static FoleyType CHOMP_SOFT = new FoleyType(4, objs25, FoleyFlags.NONE);
    	public static Object[] objs26 ={PVZSounds.SOUND_DIRT_RISE};
        public static FoleyType DIRT_RISE = new FoleyType(5, objs26, FoleyFlags.NONE);
    	public static Object[] objs27 ={PVZSounds.SOUND_TAP};
        public static FoleyType TAP = new FoleyType(0, objs27, FoleyFlags.NONE);
    	public static Object[] objs28 ={PVZSounds.SOUND_PUFF};
        public static FoleyType PUFF = new FoleyType(10, objs28, FoleyFlags.NONE);
    	public static Object[] objs29 ={PVZSounds.SOUND_DIGGER_ZOMBIE};
        public static FoleyType DIGGER = new FoleyType(0, objs29, new FoleyFlags(((FoleyFlags.LOOP | FoleyFlags.ONE_AT_A_TIME) | FoleyFlags.MUTE_ON_PAUSE)));
    	public static Object[] objs30 ={PVZSounds.SOUND_SHIELDHIT, PVZSounds.SOUND_SHIELDHIT2};
        public static FoleyType SHIELD_HIT = new FoleyType(10, objs30, FoleyFlags.NONE);
    	public static Object[] objs31 ={PVZSounds.SOUND_CRAZYDAVESHORT1, PVZSounds.SOUND_CRAZYDAVESHORT2, PVZSounds.SOUND_CRAZYDAVESHORT3};
        public static FoleyType CRAZYDAVESHORT = new FoleyType(0, objs31, new FoleyFlags(FoleyFlags.DONT_REPEAT));
    	public static Object[] objs32 ={PVZSounds.SOUND_FROZEN};
        public static FoleyType FROZEN = new FoleyType(0, objs32, FoleyFlags.NONE);
    	public static Object[] objs33 ={PVZSounds.SOUND_SHOVEL};
        public static FoleyType SHOVEL = new FoleyType(5, objs33, FoleyFlags.NONE);
    	public static Object[] objs34 ={PVZSounds.SOUND_CRAZYDAVESCREAM2};
        public static FoleyType CRAZYDAVESCREAM2 = new FoleyType(0, objs34, FoleyFlags.NONE);
    	public static Object[] objs35 ={PVZSounds.SOUND_FUME};
        public static FoleyType FUME = new FoleyType(10, objs35, FoleyFlags.NONE);
    	public static Object[] objs36 ={PVZSounds.SOUND_CHOMP, PVZSounds.SOUND_CHOMP2};
        public static FoleyType CHOMP = new FoleyType(0, objs36, FoleyFlags.NONE);
    	public static Object[] objs37 ={PVZSounds.SOUND_BOWLING};
        public static FoleyType BOWLING = new FoleyType(0, objs37, FoleyFlags.NONE);
    	public static Object[] objs38 ={PVZSounds.SOUND_LIMBS_POP1, PVZSounds.SOUND_LIMBS_POP2, PVZSounds.SOUND_LIMBS_POP3, PVZSounds.SOUND_LIMBS_POP4, PVZSounds.SOUND_LIMBS_POP5};
        public static FoleyType LIMBS_POP = new FoleyType(10, objs38, FoleyFlags.NONE);
    	public static Object[] objs39 ={PVZSounds.SOUND_CRAZYDAVECRAZY};
        public static FoleyType CRAZYDAVECRAZY = new FoleyType(0, objs39, FoleyFlags.NONE);
    	public static Object[] objs40 ={PVZSounds.SOUND_GRAVEBUSTERCHOMP};
        public static FoleyType GRAVEBUSTERCHOMP = new FoleyType(0, objs40, new FoleyFlags(FoleyFlags.MUTE_ON_PAUSE));
    	public static Object[] objs41 ={PVZSounds.SOUND_REVERSE_EXPLOSION};
        public static FoleyType REVERSE_EXPLOSION = new FoleyType(0, objs41, FoleyFlags.NONE);
    	public static Object[] objs42 ={PVZSounds.SOUND_BUZZER};
        public static FoleyType BUZZER = new FoleyType(0, objs42, FoleyFlags.NONE);
    	public static Object[] objs43 ={PVZSounds.SOUND_CHERRYBOMB};
        public static FoleyType CHERRYBOMB = new FoleyType(0, objs43, FoleyFlags.NONE);
    	public static Object[] objs44 ={PVZSounds.SOUND_GARGANTUAR_THUMP};
        public static FoleyType THUMP = new FoleyType(2, objs44, FoleyFlags.NONE);
    	public static Object[] objs45 ={PVZSounds.SOUND_THROW1, PVZSounds.SOUND_THROW2, PVZSounds.SOUND_THROW3};
        public static FoleyType THROW = new FoleyType(10, objs45, FoleyFlags.NONE);
    	public static Object[] objs46 ={PVZSounds.SOUND_BIGCHOMP};
        public static FoleyType BIGCHOMP = new FoleyType(-2, objs46, FoleyFlags.NONE);
    	public static Object[] objs47 ={PVZSounds.SOUND_BONK};
        public static FoleyType BONK = new FoleyType(2, objs47, FoleyFlags.NONE);
    	public static Object[] objs48 ={PVZSounds.SOUND_READYSETPLANT};
        public static FoleyType READYSETPLANT = new FoleyType(0, objs48, FoleyFlags.NONE);
    	public static Object[] objs49 ={PVZSounds.SOUND_GRASSSTEP};
        public static FoleyType GRASS_STEP = new FoleyType(0, objs49, FoleyFlags.NONE);
    	public static Object[] objs50 ={PVZSounds.SOUND_LAWNMOWER};
        public static FoleyType LAWNMOWER = new FoleyType(10, objs50, FoleyFlags.NONE);
    	public static Object[] objs51 ={PVZSounds.SOUND_CRAZYDAVELONG1, PVZSounds.SOUND_CRAZYDAVELONG2, PVZSounds.SOUND_CRAZYDAVELONG3};
        public static FoleyType CRAZYDAVELONG = new FoleyType(0, objs51, new FoleyFlags(FoleyFlags.DONT_REPEAT));
    	public static Object[] objs52 ={PVZSounds.SOUND_PAUSE};
        public static FoleyType PAUSE = new FoleyType(0, objs52, FoleyFlags.NONE);
    	public static Object[] objs53 ={PVZSounds.SOUND_SWING};
        public static FoleyType SWING = new FoleyType(2, objs53, FoleyFlags.NONE);
    	public static Object[] objs54 ={PVZSounds.SOUND_PLANTGROW};
        public static FoleyType PLANTGROW = new FoleyType(-2, objs54, FoleyFlags.NONE);
    	public static Object[] objs55 ={PVZSounds.SOUND_BOWLINGIMPACT};
        public static FoleyType BOWLINGIMPACT = new FoleyType(-3, objs55, FoleyFlags.NONE);
    	public static Object[] objs56 ={PVZSounds.SOUND_SQUASH_HMM, PVZSounds.SOUND_SQUASH_HMM, PVZSounds.SOUND_SQUASH_HMM2};
        public static FoleyType SQUASH_HMM = new FoleyType(2, objs56, FoleyFlags.NONE);
    	public static Object[] objs57 ={PVZSounds.SOUND_TAP2};
        public static FoleyType DROP = new FoleyType(0, objs57, FoleyFlags.NONE);
    	public static Object[] objs58 ={PVZSounds.SOUND_AWOOGA};
        public static FoleyType AWOOGA = new FoleyType(0, objs58, FoleyFlags.NONE);
    	public static Object[] objs59 ={PVZSounds.SOUND_GROAN, PVZSounds.SOUND_GROAN2, PVZSounds.SOUND_GROAN3, PVZSounds.SOUND_GROAN4, PVZSounds.SOUND_GROAN5, PVZSounds.SOUND_GROAN6};
        public static FoleyType GROAN = new FoleyType(0, objs59, FoleyFlags.NONE);
    	public static Object[] objs60 ={PVZSounds.SOUND_GULP};
        public static FoleyType GULP = new FoleyType(0, objs60, FoleyFlags.NONE);
    	public static Object[] objs61 ={PVZSounds.SOUND_SEEDLIFT};
        public static FoleyType SEEDLIFT = new FoleyType(0, objs61, FoleyFlags.NONE);
    	public static Object[] objs62 ={PVZSounds.SOUND_SCREAM};
        public static FoleyType SCREAM = new FoleyType(0, objs62, FoleyFlags.NONE);

    }


